apiVersion: apps/v1
kind: Deployment
    # Opis deploymentu, nepovine 
metadata: 
  name: innovate
  namespace: develop
    # namespave: myapp# annotation su nepovine udaje pouzite na popis deploymentu,k tore ale niesu pouzite ako identifikatory pri query 
spec:  
  replicas: 1 
  strategy:    
     # type: Recreate    
    type: RollingUpdate
    rollingUpdate:      
      maxUnavailable: 0     
      maxSurge: 1    
     # type: RollingUpdate    # rollingUpdate:    #   maxUnavailable: 10%    
     #   maxSurge: 10%# Selector sluzi na prepojenie servicov s deploymentami 
  selector:    
    matchLabels:      
      app: innovate
  template:   
    metadata:     
      labels:
    # Labels  - Identifying metadata that you can use to sort and select sets of API objects. Labels have many applications, including the following:
    # SLuzia na identifikaciu objektov v API calloch
    # kubectl get deployments --selector=app=innovate    
        app: innovate
    spec:     
      containers:     
      - name: innovate
        image: fsainfrasochabranislavregistry.azurecr.io/socha-cicd.westeurope.azurecontainer.io/innovate:latest
        ports:       
        - containerPort: 80  
        imagePullPolicy: Always
        resources:          
          requests:           
            memory: "64Mi"         
            cpu: "100m"    
          limits:        
            memory: "128Mi"     
            cpu: "500m"